spring:
  application:
    name: DB_document

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homework
    username: root
    password: 147852963!Cky

mybatis:
  type-aliases-package: com.example.document.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
      # 开启驼峰命名映射
    map-underscore-to-camel-case: true